In [1]:
# Testing if the energy deposition works

In [1]:
%pylab widget
%load_ext autoreload
%autoreload 2

Populating the interactive namespace from numpy and matplotlib


In [2]:
import fastcat as fc

In [33]:
nviews = 2

s = fc.Spectrum()
s.load('Al_spectrum_6')
kernel = fc.Detector(s,'CsI-784-micrometer')
angles = np.linspace(0,np.pi*2,nviews)

phantom = fc.Catphan_404(hi_res=False)
phantom.phan_map = ['air'] + ['water']*12
phantom.return_projs(kernel,s,angles,det_on=True,mgy=1.39*300/nviews)

[2021-07-19 17:43:47,540] {phantoms.py:649} INFO - Phantom is low resolution
[2021-07-19 17:43:47,632] {simulate.py:467} INFO - Running Simulations
[2021-07-19 17:43:47,632] {simulate.py:482} INFO -     Simulating 10 keV
[2021-07-19 17:43:47,800] {simulate.py:482} INFO -     Simulating 20 keV
[2021-07-19 17:43:47,940] {simulate.py:482} INFO -     Simulating 30 keV
[2021-07-19 17:43:48,084] {simulate.py:482} INFO -     Simulating 40 keV
[2021-07-19 17:43:48,228] {simulate.py:482} INFO -     Simulating 50 keV
[2021-07-19 17:43:48,370] {simulate.py:482} INFO -     Simulating 60 keV
[2021-07-19 17:43:48,511] {simulate.py:482} INFO -     Simulating 70 keV
[2021-07-19 17:43:48,658] {simulate.py:482} INFO -     Simulating 80 keV
[2021-07-19 17:43:48,806] {simulate.py:482} INFO -     Simulating 90 keV
[2021-07-19 17:43:48,945] {simulate.py:482} INFO -     Simulating 100 keV
[2021-07-19 17:43:49,090] {simulate.py:482} INFO -     Simulating 300 keV
[2021-07-19 17:43:49,234] {simulate.py:482} INF

In [31]:
plt.plot(np.mean(test[0],0))

In [29]:
plt.figure()
plt.plot(np.mean(test[0],0))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [35]:
plt.figure()
ints = []
for intensity in phantom.intensities:
    
    plt.plot(np.mean(intensity[0],0))
    ints.append(np.mean(intensity[0],0))
    plt.legend(original_energies_keV)

plt.plot(np.sum(ints,0))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [104]:
plt.figure()
ints = []

original_energies_keV = np.array(
    [
        10,
        20,
        30,
        40,
        50,
        60,
        70,
        80,
        90,
        100,
        300,
        500,
        700,
        900,
        1000,
        2000,
        4000,
        6000,
    ]
)
for intensity in phantom.intensities:
    
    plt.plot(np.mean(intensity[0],0))
    ints.append(np.mean(intensity[0],0))
    plt.legend(original_energies_keV)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

# Now lets do a simple test case

In [3]:
nviews = 2

s = fc.Spectrum()
s.x = [39.9999,40,50,50.00001]
s.y = [0,0.5,0.5,0]

kernel = fc.Detector(s,'CsI-784-micrometer')
angles = np.linspace(0,np.pi*2,nviews)

phantom = fc.Catphan_404(hi_res=False)
phantom.phan_map = ['air'] + ['water']*12
phantom.return_projs(kernel,s,angles,det_on=True,mgy=1.39*300/nviews)

[2021-07-20 15:58:21,719] {phantoms.py:649} INFO - Phantom is low resolution
[2021-07-20 15:58:21,817] {simulate.py:531} INFO - Running Simulations
[2021-07-20 15:58:21,817] {simulate.py:555} INFO -     Simulating 40 keV
[2021-07-20 15:58:22,009] {simulate.py:555} INFO -     Simulating 50 keV
[2021-07-20 15:58:22,152] {simulate.py:741} INFO - Weighting simulations
[2021-07-20 15:58:22,152] {simulate.py:813} INFO -     Added noise 3177481.984779275 times reference


/home/xcite/fastcat-0.0.1/fastcat/simulate.py:736: RuntimeWarning: invalid value encountered in true_divide
  self.weights_small2 = (w_fluence_times_energy/ w_fluence_times_p_detected_energy)/np.nansum(w_fluence_times_energy / w_fluence_times_p_detected_energy)


In [91]:
[2021-07-20 14:40:57,771] {phantoms.py:649} INFO - Phantom is low resolution
[2021-07-20 14:40:57,860] {simulate.py:531} INFO - Running Simulations
[2021-07-20 14:40:57,860] {simulate.py:555} INFO -     Simulating 40 keV
> /home/xcite/fastcat-0.0.1/fastcat/simulate.py(682)return_projs()
    681 
--> 682             noise_temp = np.random.poisson(np.abs(int_temp)) - int_temp
    683 

ipdb>  int_temp[0,10,10:20]

array([333.42566247, 333.42954778, 333.64206925, 333.60530432,
       333.71290527, 333.86043343, 333.62611801, 333.88965164,
       333.99226865, 333.99020487])

ipdb>  continue

> /home/xcite/fastcat-0.0.1/fastcat/simulate.py(547)return_projs()
    546 
--> 547         for jj, energy in enumerate(MC_energies_keV):
    548 

ipdb>  (int_temp * w_fluence_times_energy[jj] / w_fluence_times_p_detected_energy[jj])[0,10,10:20]

array([311.74383844, 311.7474711 , 311.94617283, 311.91179863,
       312.01240256, 312.15033734, 311.93125887, 312.17765557,
       312.27359966, 312.27167008])


[0.000e+00 1.000e+00 2.000e+00 ... 5.998e+03 5.999e+03 6.000e+03]


In [92]:
plt.figure()
plt.plot(phantom.weights_small)
plt.plot(phantom.weights_small2)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [93]:
print(phantom.weights_small)
print(phantom.weights_small2)
print(phantom.weights_small3)

[0.         0.         0.         0.48072397 0.51927603 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.        ]
[       nan        nan        nan 0.46660205 0.53339795        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan]
[0.         0.         0.         0.51415838 0.48584162 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.        ]


In [51]:
print(np.array([.5*.4/0.9,0.5*0.5/0.9])/(.5*.4/0.9+0.5*0.5/0.9))

[0.44444444 0.55555556]


In [75]:
print(phantom.dep[3:5])

w = phantom.dep[3:5]/np.sum(phantom.dep[3:5])
print(w)

[36042.890625   40992.69140625]
[0.46787328 0.53212672]


In [72]:
print(np.array([.5*w[0],0.5*w[1]])/(.5*w[0]+0.5*w[1]))

[0.46787328 0.53212672]


In [111]:
plt.figure()
plt.semilogx(original_energies_keV[2:],phantom.dep/original_energies_keV[2:]/1000)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

ValueError: operands could not be broadcast together with shapes (18,) (16,) 

In [113]:

plt.figure()
plt.semilogx(original_energies_keV,phantom.dep/original_energies_keV/1000)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [115]:

plt.figure()
plt.semilogx(original_energies_keV,phantom.dep/1000)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …