In [1]:
# Testing if the energy deposition works

In [2]:
%pylab widget
%load_ext autoreload
%autoreload 2

Populating the interactive namespace from numpy and matplotlib


In [3]:
import fastcat as fc

In [33]:
nviews = 2

s = fc.Spectrum()
s.load('Al_spectrum_6')
kernel = fc.Detector(s,'CsI-784-micrometer')
angles = np.linspace(0,np.pi*2,nviews)

phantom = fc.Catphan_404(hi_res=False)
phantom.phan_map = ['air'] + ['water']*12
phantom.return_projs(kernel,s,angles,det_on=True,mgy=1.39*300/nviews)

[2021-07-19 17:43:47,540] {phantoms.py:649} INFO - Phantom is low resolution
[2021-07-19 17:43:47,632] {simulate.py:467} INFO - Running Simulations
[2021-07-19 17:43:47,632] {simulate.py:482} INFO -     Simulating 10 keV
[2021-07-19 17:43:47,800] {simulate.py:482} INFO -     Simulating 20 keV
[2021-07-19 17:43:47,940] {simulate.py:482} INFO -     Simulating 30 keV
[2021-07-19 17:43:48,084] {simulate.py:482} INFO -     Simulating 40 keV
[2021-07-19 17:43:48,228] {simulate.py:482} INFO -     Simulating 50 keV
[2021-07-19 17:43:48,370] {simulate.py:482} INFO -     Simulating 60 keV
[2021-07-19 17:43:48,511] {simulate.py:482} INFO -     Simulating 70 keV
[2021-07-19 17:43:48,658] {simulate.py:482} INFO -     Simulating 80 keV
[2021-07-19 17:43:48,806] {simulate.py:482} INFO -     Simulating 90 keV
[2021-07-19 17:43:48,945] {simulate.py:482} INFO -     Simulating 100 keV
[2021-07-19 17:43:49,090] {simulate.py:482} INFO -     Simulating 300 keV
[2021-07-19 17:43:49,234] {simulate.py:482} INF

In [31]:
plt.plot(np.mean(test[0],0))

In [29]:
plt.figure()
plt.plot(np.mean(test[0],0))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [35]:
plt.figure()
ints = []
for intensity in phantom.intensities:
    
    plt.plot(np.mean(intensity[0],0))
    ints.append(np.mean(intensity[0],0))
    plt.legend(original_energies_keV)

plt.plot(np.sum(ints,0))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [56]:
plt.figure()
ints = []

original_energies_keV = np.array(
    [
        10,
        20,
        30,
        40,
        50,
        60,
        70,
        80,
        90,
        100,
        300,
        500,
        700,
        900,
        1000,
        2000,
        4000,
        6000,
    ]
)
for intensity in phantom.intensities:
    
    plt.plot(np.mean(intensity[0],0))
    ints.append(np.mean(intensity[0],0))
    plt.legend(original_energies_keV)

/home/xcite/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  """Entry point for launching an IPython kernel.


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

# Now lets do a simple test case

In [ ]:
nviews = 2

s = fc.Spectrum()
s.x = [39.9999,40,50,50.00001]
s.y = [0,0.5,0.5,0]

kernel = fc.Detector(s,'CsI-784-micrometer')
angles = np.linspace(0,np.pi*2,nviews)

phantom = fc.Catphan_404(hi_res=False)
phantom.phan_map = ['air'] + ['water']*12
phantom.return_projs(kernel,s,angles,det_on=True,mgy=1.39*300/nviews)

[2021-07-20 11:38:42,469] {phantoms.py:649} INFO - Phantom is low resolution
> /home/xcite/fastcat-0.0.1/fastcat/simulate.py(332)return_projs()
    331         import ipdb; ipdb.set_trace()
--> 332         fluence_norm = spectra.y / np.sum(spectra.y)
    333 



ipdb>  weights_xray_small


array([0.        , 0.        , 0.        , 0.51415838, 0.48584162,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        ])


ipdb>  weights_energies


array([0.        , 0.        , 0.        , 0.48072397, 0.51927603,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        ])


ipdb>  weights_xray


array([0., 0., 0., ..., 0., 0., 0.])


ipdb>  weights_xray[:100]


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.45053613, 0.44241429, 0.43429245, 0.4261706 , 0.41804876,
       0.40992691, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [91]:
print(np.linspace(0, 6000, 6001))

[0.000e+00 1.000e+00 2.000e+00 ... 5.998e+03 5.999e+03 6.000e+03]


In [92]:
plt.figure()
plt.plot(phantom.weights_small)
plt.plot(phantom.weights_small2)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [93]:
print(phantom.weights_small)
print(phantom.weights_small2)
print(phantom.weights_small3)

[0.         0.         0.         0.48072397 0.51927603 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.        ]
[       nan        nan        nan 0.46660205 0.53339795        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan]
[0.         0.         0.         0.51415838 0.48584162 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.        ]


In [51]:
print(np.array([.5*.4/0.9,0.5*0.5/0.9])/(.5*.4/0.9+0.5*0.5/0.9))

[0.44444444 0.55555556]


In [75]:
print(phantom.dep[3:5])

w = phantom.dep[3:5]/np.sum(phantom.dep[3:5])
print(w)

[36042.890625   40992.69140625]
[0.46787328 0.53212672]


In [72]:
print(np.array([.5*w[0],0.5*w[1]])/(.5*w[0]+0.5*w[1]))

[0.46787328 0.53212672]
